# Generated by Django 3.0 on 2021-05-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=9)),
                ('edad', models.IntegerField(default=0)),
                ('peso', models.FloatField(default=0.0)),
                ('altura', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.IntegerField(default=0)),
                ('dato_adicional', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.IntegerField(default=0)),
                ('dato_adicional', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('fk_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triaje.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triaje.Informe')),
                ('fk_patologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.Patologia')),
                ('fk_sintoma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='triaje.Sintoma')),
            ],
        ),
    ]
